import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { NavbarComponent } from "../components/Navbar";

const ContactPage: NextPage = () => {
  const [fname, setFname] = useState("");

  const handleSubmit = (e: any) => {
    e.preventDefault();
    alert(`FIRST NAME: ${fname}`);
  };

  return (
    <div>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <h1>Contact Us</h1>
      <form className="border-2" onSubmit={handleSubmit}>
        <label htmlFor="fname">First name:</label>
        <br />
        <input
          onChange={(e) => setFname(e.target.value)}
          type="text"
          id="fname"
          name="fname"
          className="border-2"
          defaultValue=""
        />
        <br />
        <button type="submit" className="bg-green-400 px-4 py-3">
          Submit
        </button>
      </form>
    </div>
  );
};

export default ContactPage;
