import type { NextPage } from "next";
import Head from "next/head";
import { NavbarComponent } from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarComponent />
      <h1>Home</h1>
    </div>
  );
};

export default Home;
